### GENERAL SETTINGS ###

# Site settings
title: AceLewis.com
description: "A website for me to do things with"
blog_name: "Alexander Lewis (AceLewis)"
analytics: UA-70463146-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "https://acelewis.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

newtab: :target="_blank"
### CONTACT SETTINGS ###
twitter_username: "_AceLewis"
# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: Twitter
    fa_icon: <i class="fa fa-twitter"></i>
    url: https://twitter.com/_AceLewis
  - title: Reddit
    fa_icon: <i class="fa fa-reddit-alien"></i>
    url: https://reddit.com/u/_AceLewis
  - title: Github
    fa_icon: <i class="fa fa-github"></i>
    url: https://github.com/AceLewis
  - title: YouTube
    fa_icon: <i class="fa fa-youtube"></i>
    url: https://www.youtube.com/channel/UCRn4xTmE0IIEPsdt6R0gzcw

contact:
  - title: Twitter
    url: https://twitter.com/_AceLewis
    site_name: _AceLewis
  - title: Reddit
    url: https://reddit.com/u/_AceLewis
    site_name: _AceLewis



# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Nottingham
    - United Kingdom.
email: N/A
tel: N/A


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Alexander Lewis
    # position: Owner
    text: I like physics/science, technology, programming, data, open source, and the internet.
    img: AceLewisProfilePic.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Removed due to spam
      - title: twitter
        url: http://twitter.com/_AceLewis


# FOOTER ABOUT, Shown in footer on every page
about_footer: "I am interested in Physics, Maths, Programming and also play a few games in my spare time. I have an interest in data and have made webscrapers to gather and process information, I am currently looking into nice ways to display information easily in infographics using Python. I can code in Matlab, Python and have also made a Steam trading bot in Node.JS."
about_home: "I am interested in Physics, Maths, Programming and also play a few games in my spare time. I have an interest in data and have made webscrapers to gather and process information, I am currently looking into nice ways to display information easily in infographics using Python. I can code in Matlab, Python and have also made a Steam trading bot in Node.JS."
about_about: "
I love Physics and also have a big interest in programming, before university I did a little bit of
programming and I enjoyed it. Whilst at university I was taught Matlab
a mathematical and statistical language aimed at scientists and engineers, Matlab
further infulenced me into getting into programming as a hobby.
I have done a few projects in Matlab however outside of Physics I do my projects
in other languages such as Python and Node.js as they are free and opensource
so anyone can use what I make in them.
</p><p>
I also enjoy skiing, cycling, magic tricks, and I used to love playing football but I have not
got the time to play in a team anymore.
</p>"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "I am interested in Physics, Maths, Programming and also play a few games in my spare time. I have an interest in data and have made webscrapers to gather and process information, I am currently looking into nice ways to display information easily in infographics using Python. I can code in Matlab, Python and have also made a Steam trading bot in Node.JS."
    author: Alex Lewis (AceLewis)

# CONTACT PAGE
about_contact: "You can contact me on any of the sites listed, note I no longer make Steam Trade bots for people so please do not contact me about purchasing them however if you want a bit of help with Steam's API I will gladly help you out."
where_to_contact_text: "You can contact me on any of the services provided, note I have not included my email address as I do not want to be spammed."
